More protobufs, and registered in the registrery
sw8f17/app pull request #11
Opened 2017-05-04 10:39 UTC by VirtualSatai

2017-05-05 08:43 UTC, mathiassmichno requested changes

2017-05-05 08:43 UTC, mathiassmichno commented on app/src/proto/metadata.proto
> +    int32 duration = 5;
er det granuleret nok med et sekund?

2017-05-05 09:40 UTC, VirtualSatai commented on app/src/proto/metadata.proto
> +    int32 duration = 5;
Det er til at vise i UI, der er det kun sekunder vi viser anw.

2017-05-08 15:07 UTC, mathiassmichno approved these changes

2017-05-09 18:04 UTC, VirtualSatai commented
Bliver en del af et andet PR

2017-05-09 18:04 UTC, closed without merging